sudo:
  - required

language:
  - bash

services:
  - docker

before_install:
  - git clone https://github.com/BaloghTamas/Docker-nginx-rtmp.git ~/Docker-nginx-rtmp

script:
  - ./build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi
